version: 1.0.{build}
environment:
  matrix:
  - GHCVER: 8.10.1
  - GHCVER: 8.8.3
  - GHCVER: 8.6.5
  - GHCVER: 8.4.4
install:
  - git submodule update --init --recursive
  - choco install -y haskell-stack
  - choco install -y cabal
  - choco install ghc --version %GHCVER%
  - choco install -y shellcheck
  - refreshenv
  - "set PATH=C:\\ProgramData\\chocolatey\\lib\\ghc\\tools\\ghc-%GHCVER%\\bin;C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
  - shellcheck --version
  - stack --version
  - cabal --version
  - ghc --version


cache:
  - '%LOCALAPPDATA%\Programs\stack\'
  - c:\sr
  - '%APPDATA%\cabal'

before_build:
  - cabal v2-update

build_script:
  - cabal v2-build -w ghc-%GHCVER%.exe --disable-tests --disable-benchmarks exes

before_test:
  - cabal v2-build --enable-tests -w ghc-%GHCVER%.exe tests
  # sanity check the wrappers
  - shellcheck wrappers/cabal
  - ghc -hide-all-packages -package base -package directory -package process -Wall -Werror wrappers/cabal.hs -o CabalWrapper -hidir %TMP% -odir %TMP%


test_script:
  - cabal v2-test -w ghc-%GHCVER%.exe
