name: Build and Test

on: [push, pull_request]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.1', '8.8.3', '8.6.5', '8.4.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            ghc: '8.8.3' # fails due to segfault
          - os: macOS-latest
            ghc: '8.4.4' # fails due to ghc panic

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
        enable-stack: true

    - name: Cache Cabal
      uses: actions/cache@v1.2.0
      with:
        path: ~/.cabal
        key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal-0

    - name: Cache Stack
      uses: actions/cache@v1.2.0
      with:
        path: ~/.stack
        key: ${{ runner.OS }}-${{ matrix.ghc }}-stack-0

    - name: Setup stack
      run: stack setup

    - name: Update cabal
      run: cabal update

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2f2aa0d
      if: matrix.os == 'ubuntu-latest'
      with:
        ignore: tests

    - name: Build
      run: cabal build

    - name: Display the path
      run: echo %PATH%
      shell: cmd

    - name: Test
      run: cabal test
      shell: cmd
